import type { Subject } from "@/types/content";

/**
 * Plan de estudios completo: Licenciatura en Gestión de las Tecnologías de la
 * Información (UADE), que incluye como título intermedio la Tecnicatura
 * Universitaria en Desarrollo de Software.
 *
 * `year` = año dentro del plan de la Licenciatura (el plan completo).
 * `tecnicaturaYear` = año dentro del plan de la Tecnicatura, solo si la
 * materia también forma parte de ese título intermedio.
 *
 * Las correlatividades (`prerequisites`) son una aproximación ilustrativa
 * basada en la progresión lógica de contenidos, no la tabla oficial de
 * correlatividades de la universidad.
 */
export const subjects: Subject[] = [
  // ---------- AÑO 1 ----------
  {
    code: "3.4.225",
    name: { es: "Introducción a la Algoritmia", en: "Introduction to Algorithms" },
    hours: 68,
    year: 1,
    tecnicaturaYear: 1,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 6,
    mode: "aprobado",
  },
  {
    code: "3.4.164",
    name: { es: "Sistemas de Información I", en: "Information Systems I" },
    hours: 68,
    year: 1,
    tecnicaturaYear: 1,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 7,
    mode: "promocion",
  },
  {
    code: "3.4.072",
    name: { es: "Arquitectura de Computadores", en: "Computer Architecture" },
    hours: 68,
    year: 1,
    tecnicaturaYear: 1,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 7,
    mode: "aprobado",
  },
  {
    code: "1.2.001",
    name: { es: "Marketing", en: "Marketing" },
    hours: 68,
    year: 1,
    careers: ["licenciatura"],
    status: "aprobada",
    grade: 8,
    mode: "promocion",
  },
  {
    code: "3.4.226",
    name: { es: "Diseño y Desarrollo Web", en: "Web Design and Development" },
    hours: 68,
    year: 1,
    tecnicaturaYear: 1,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 7,
    mode: "promocion",
    prerequisites: ["3.4.164"],
  },
  {
    code: "3.4.227",
    name: { es: "Algoritmos y Estructuras de Datos I", en: "Algorithms and Data Structures I" },
    hours: 68,
    year: 1,
    tecnicaturaYear: 1,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 5,
    mode: "aprobado",
    prerequisites: ["3.4.225"],
  },
  {
    code: "3.4.207",
    name: { es: "Sistemas de Información II", en: "Information Systems II" },
    hours: 68,
    year: 1,
    tecnicaturaYear: 1,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 6,
    mode: "aprobado",
    prerequisites: ["3.4.164"],
  },
  {
    code: "3.4.075",
    name: { es: "Sistemas Operativos", en: "Operating Systems" },
    hours: 68,
    year: 1,
    tecnicaturaYear: 1,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 9,
    mode: "promocion",
    prerequisites: ["3.4.072"],
  },
  {
    code: "3.1.024",
    name: { es: "Matemática Discreta", en: "Discrete Mathematics" },
    hours: 68,
    year: 1,
    careers: ["licenciatura"],
    status: "final-pendiente",
    note: { es: "Regularizada, final pendiente", en: "Regularized, final exam pending" },
  },
  {
    code: "3.4.228",
    name: { es: "Testing de Aplicaciones", en: "Application Testing" },
    hours: 68,
    year: 1,
    tecnicaturaYear: 1,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 7,
    mode: "aprobado",
    prerequisites: ["3.4.227"],
  },

  // ---------- AÑO 2 ----------
  {
    code: "3.4.229",
    name: { es: "Algoritmos y Estructuras de Datos II", en: "Algorithms and Data Structures II" },
    hours: 68,
    year: 2,
    tecnicaturaYear: 2,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 10,
    mode: "aprobado",
    prerequisites: ["3.4.227"],
  },
  {
    code: "3.4.208",
    name: { es: "Paradigma Orientado a Objetos", en: "Object-Oriented Paradigm" },
    hours: 68,
    year: 2,
    tecnicaturaYear: 2,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 9,
    mode: "aprobado",
    prerequisites: ["3.4.227"],
  },
  {
    code: "3.4.230",
    name: { es: "Redes de Datos", en: "Data Networks" },
    hours: 68,
    year: 2,
    tecnicaturaYear: 2,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 7,
    mode: "aprobado",
    prerequisites: ["3.4.075"],
  },
  {
    code: "1.4.076",
    name: { es: "Fundamentos de Economía", en: "Fundamentals of Economics" },
    hours: 68,
    year: 2,
    careers: ["licenciatura"],
    status: "pendiente",
    prerequisites: ["1.2.001"],
  },
  {
    code: "3.4.131",
    name: { es: "Gestión de Personas en Org. de Tecnología", en: "People Management in Tech Organizations" },
    hours: 68,
    year: 2,
    tecnicaturaYear: 3,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 8,
    mode: "promocion",
    note: { es: "Optativa de la Tecnicatura", en: "Elective in the Technical Degree" },
  },
  {
    code: "3.4.231",
    name: { es: "Diseño y Análisis de Algoritmos", en: "Algorithm Design and Analysis" },
    hours: 68,
    year: 2,
    tecnicaturaYear: 2,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 9,
    mode: "aprobado",
    prerequisites: ["3.4.229"],
  },
  {
    code: "3.4.142",
    name: { es: "Dirección de Proyectos de Tecnología", en: "Technology Project Management" },
    hours: 68,
    year: 2,
    careers: ["licenciatura"],
    status: "aprobada",
    grade: 9,
    mode: "promocion",
    prerequisites: ["3.4.131"],
  },
  {
    code: "3.4.209",
    name: { es: "Ingeniería de Datos I", en: "Data Engineering I" },
    hours: 68,
    year: 2,
    tecnicaturaYear: 2,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 8,
    mode: "aprobado",
    prerequisites: ["3.4.207"],
  },
  {
    code: "3.4.214",
    name: { es: "Ingeniería de Software", en: "Software Engineering" },
    hours: 68,
    year: 2,
    careers: ["licenciatura"],
    status: "pendiente",
    prerequisites: ["3.4.208"],
  },
  {
    code: "1.1.093",
    name: { es: "Liderazgo y Negociación", en: "Leadership and Negotiation" },
    hours: 68,
    year: 2,
    careers: ["licenciatura"],
    status: "final-pendiente",
    note: { es: "Regularizada, final pendiente", en: "Regularized, final exam pending" },
    prerequisites: ["3.4.131"],
  },

  // ---------- AÑO 3 ----------
  {
    code: "3.4.082",
    name: { es: "Aplicaciones Interactivas", en: "Interactive Applications" },
    hours: 68,
    year: 3,
    tecnicaturaYear: 2,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 8,
    mode: "promocion",
    prerequisites: ["3.4.226", "3.4.208"],
  },
  {
    code: "3.4.210",
    name: { es: "Proceso de Desarrollo de Software", en: "Software Development Process" },
    hours: 68,
    year: 3,
    tecnicaturaYear: 2,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 7,
    mode: "aprobado",
    prerequisites: ["3.4.214"],
  },
  {
    code: "3.4.092",
    name: { es: "Seg. e Integ. de la Información", en: "Information Security and Integration" },
    hours: 68,
    year: 3,
    careers: ["licenciatura"],
    status: "pendiente",
    prerequisites: ["3.4.230"],
  },
  {
    code: "3.1.049",
    name: { es: "Probabilidad y Estadística", en: "Probability and Statistics" },
    hours: 68,
    year: 3,
    careers: ["licenciatura"],
    status: "pendiente",
    prerequisites: ["3.1.024"],
  },
  {
    code: "2.4.216",
    name: { es: "Examen de Inglés", en: "English Exam" },
    hours: 0,
    year: 3,
    careers: ["licenciatura"],
    status: "pendiente",
  },
  {
    code: "3.4.232",
    name: {
      es: "Trabajo Integrador Final",
      en: "Final Integrative Project",
    },
    hours: 218,
    year: 3,
    tecnicaturaYear: 3,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 5,
    mode: "equivalencia",
    note: {
      es: "En la Licenciatura equivale internamente a \"Seminario de Gestión de Tecnología\" (3.4.233)",
      en: "Internally equivalent to \"Technology Management Seminar\" (3.4.233) in the Bachelor's plan",
    },
    prerequisites: ["3.4.210", "3.4.213"],
  },
  {
    code: "3.4.213",
    name: { es: "Ingeniería de Datos II", en: "Data Engineering II" },
    hours: 68,
    year: 3,
    tecnicaturaYear: 3,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 7,
    mode: "aprobado",
    prerequisites: ["3.4.209"],
  },
  {
    code: "3.4.139",
    name: { es: "Evaluación de Proyectos de Tecnología", en: "Technology Project Evaluation" },
    hours: 68,
    year: 3,
    careers: ["licenciatura"],
    status: "pendiente",
    prerequisites: ["3.4.142"],
  },
  {
    code: "3.1.056",
    name: { es: "Estadística Avanzada", en: "Advanced Statistics" },
    hours: 68,
    year: 3,
    careers: ["licenciatura"],
    status: "pendiente",
    prerequisites: ["3.1.049"],
  },

  // ---------- AÑO 4 ----------
  {
    code: "3.4.216",
    name: { es: "Desarrollo de Aplicaciones I", en: "Application Development I" },
    hours: 108,
    year: 4,
    tecnicaturaYear: 3,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 8,
    mode: "promocion",
    prerequisites: ["3.4.082", "3.4.210"],
  },
  {
    code: "3.4.141",
    name: { es: "Seguridad de Procesos y Aplicaciones", en: "Process and Application Security" },
    hours: 68,
    year: 4,
    careers: ["licenciatura"],
    status: "pendiente",
    prerequisites: ["3.4.092"],
  },
  {
    code: "3.4.217",
    name: { es: "Ciencia de Datos", en: "Data Science" },
    hours: 68,
    year: 4,
    careers: ["licenciatura"],
    status: "aprobada",
    grade: 8,
    mode: "aprobado",
    prerequisites: ["3.4.213"],
  },
  {
    code: "3.4.220",
    name: { es: "Tendencias Tecnológicas", en: "Technology Trends" },
    hours: 68,
    year: 4,
    careers: ["licenciatura"],
    status: "aprobada",
    grade: 9,
    mode: "aprobado",
    prerequisites: ["3.4.214"],
  },
  {
    code: "3.4.218",
    name: { es: "Desarrollo de Aplicaciones II", en: "Application Development II" },
    hours: 168,
    year: 4,
    careers: ["licenciatura"],
    status: "pendiente",
    prerequisites: ["3.4.216"],
  },
  {
    code: "3.4.135",
    name: { es: "Tecnología e Innovación", en: "Technology and Innovation" },
    hours: 68,
    year: 4,
    careers: ["licenciatura"],
    status: "pendiente",
    prerequisites: ["3.4.220"],
  },
  {
    code: "3.4.221",
    name: { es: "Negocios Tecnológicos", en: "Technology Business" },
    hours: 68,
    year: 4,
    tecnicaturaYear: 3,
    careers: ["tecnicatura", "licenciatura"],
    status: "aprobada",
    grade: 8,
    mode: "promocion",
    note: { es: "Optativa de la Tecnicatura", en: "Elective in the Technical Degree" },
    prerequisites: ["3.4.142"],
  },
  {
    code: "2.3.056",
    name: { es: "Derecho Informático", en: "IT Law" },
    hours: 68,
    year: 4,
    careers: ["licenciatura"],
    status: "pendiente",
  },
];

/** Promedio oficial de la Tecnicatura (ya completa), según el sistema académico. */
export const TECNICATURA_PROMEDIO = 7.14;

export const TECNICATURA_TITULO = {
  es: "Técnico Universitario en Desarrollo de Software",
  en: "Software Development University Technician",
};

export const LICENCIATURA_TITULO = {
  es: "Licenciatura en Gestión de las Tecnologías de la Información",
  en: "B.A. in IT Management",
};

export const INSTITUCION = "UADE";
